name: Build release artifact
on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    name: Build ss2bmm.exe
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Build 7zip cmake files
        shell: cmd
        run: call Script\7zppMSVCBuild\PreBuild.bat
      
      - name: Build 7zip
        shell: cmd
        run: call Script\7zppMSVCBuild\BuildRelease.bat
        env:
          vsPlatform: Enterprise
          
      - name: Build wxWidgets
        shell: cmd
        run: call Script\wxWidgetsMSVCBuild\BuildRelease.bat
        env:
          vsPlatform: Enterprise
          
      - name: Build mod manager
        shell: cmd
        run: call VisualStudio\Build.bat
        env:
          vsPlatform: Enterprise
        
      - name: Artifact upload
        uses: actions/upload-artifact@v2
        with:
          name: SS2BMM
          path: VisualStudio\Release\ss2bmm.exe


  release:
    needs: build
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: SS2BMM
          
      - name: Set tag name to env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ss2bmm.exe
          asset_name: ss2bmm.exe
          asset_content_type: application/octet-stream
      